name: quizzapp
description: Realtime Quiz app built with Flutter & Firebase

version: 1.4.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.12.13

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  local_auth: ^0.6.2+3


  firebase_core: 0.4.4+3
  firebase_analytics: 5.0.11

  cloud_firestore: 0.13.4+2

  firebase_auth: 0.15.5+3
  google_sign_in: 4.4.1
  apple_sign_in: 0.1.0

  rxdart: 0.23.1
  provider: 4.0.5
  font_awesome_flutter: 8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter